version: '3'
services:
  database:
    restart: always
    build:
      dockerfile: database/Dockerfile
      context: .
    image: damarowahutu-postgres
    container_name: damarowahutu-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal-network

  app:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: .
    image: damarowahutu-python
    container_name: damarowahutu-app
    ports:
      - "5000:5000"
    networks:
      - internal-network
    depends_on:
      - database

networks:
    internal-network:
        driver: bridge
        name: damarowahutu-network
volumes:
  pgdata: