# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build Dockerfile for DB
      run: |
        docker build -t damarowahutu-postgres \
        --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
        -f ./database/Dockerfile .

    - name: Build Dockerfile for application
      run: |
        docker build -t damarowahutu-app \
        --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
        --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} \
        --build-arg MODE=DEVELOPMENT .

    - name: Create Docker Network
      run: |
        docker network create damarowahutu

    - name: Spin up postgres container
      run: |
        docker run --name damarowahutu-db -p 5432:5432 --network damarowahutu -d damarowahutu-postgres

    - name: Spin up flask container
      run: |
        docker run --name damarowahutu-app -p 5000:5000 --network damarowahutu -d damarowahutu-app

    - name: Run unit tests
      run: |
        docker exec damarowahutu-app python3 -m pytest tests/unit

    - name: Run integration tests
      env:
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: |
        docker exec damarowahutu-app python3 -m pytest tests/integration

    - name: Run e2e tests
      run: |
        docker exec damarowahutu-app python3 -m pytest tests/e2e
